Update login.html
DarkressX/Common pull request #75
Opened 2023-05-11 17:14 UTC by schw1erig

2023-05-11 17:36 UTC, DarkressX requested changes
This is how the site currentyl looks, if I fix the image path of the images

![image](https://github.com/DarkressX/Common/assets/30271678/93b41a32-edb6-4292-8bcd-2363b9bdb2f8)

2023-05-11 17:36 UTC, DarkressX commented on src/main/resources/static/unauthenticated/css/LoginPage.css
> -@media only screen and (max-width: 768px) {
Why is this removed? Do we no longer want to support mobile devices?

2023-05-11 17:36 UTC, DarkressX commented on src/main/resources/templates/login.html
> +    <img src="commonlogo3.png">
Here two things are happening:
1. The body tag is opened twice
2. The logo is displayed twice.
I suspect, that there is an issue

2023-05-14 10:08 UTC, schw1erig commented on src/main/resources/static/unauthenticated/css/LoginPage.css
> -@media only screen and (max-width: 768px) {
It changes automatically

2023-05-19 08:45 UTC, DarkressX approved these changes

2023-05-19 08:46 UTC, merged